# Generated by Django 5.2.5 on 2025-11-04 07:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Production ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('cast_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cast No')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('die_no', models.CharField(blank=True, max_length=100, verbose_name='Die No')),
                ('cut_length', models.CharField(blank=True, max_length=10, verbose_name='Cut Length')),
                ('section_no', models.CharField(blank=True, max_length=100, verbose_name='Section No')),
                ('section_name', models.CharField(blank=True, max_length=200, verbose_name='Section Name')),
                ('wt_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='WT Per Piece')),
                ('billet_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Billet Size')),
                ('no_of_billet', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='No Of Billet')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_reports', to='master.staff', verbose_name='Operator')),
                ('press_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='master.companypress', verbose_name='Press No')),
                ('production_plan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='planning.productionplan', verbose_name='Production Plan ID')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='master.companyshift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Online Production Report',
                'verbose_name_plural': 'Online Production Reports',
                'db_table': 'online_production_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
