# Generated by Django 5.2.5 on 2025-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('press', models.CharField(max_length=50)),
                ('die_no', models.CharField(max_length=50)),
                ('order_no', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
