# Generated by Django 5.2.5 on 2025-11-03 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_customer_address_alter_customer_contact_no_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineproductionreport',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_reports', to='master.staff', verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='onlineproductionreport',
            name='section_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section Name'),
        ),
        migrations.AddField(
            model_name='onlineproductionreport',
            name='section_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section No'),
        ),
    ]
