# Generated by Django 5.2.5 on 2025-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_onlineproductionreport_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineproductionreport',
            name='weight',
        ),
    ]
