# Generated by Django 5.2.5 on 2025-12-03 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineproductionreport',
            name='billet_size',
        ),
        migrations.RemoveField(
            model_name='onlineproductionreport',
            name='cast_no',
        ),
        migrations.RemoveField(
            model_name='onlineproductionreport',
            name='cut_length',
        ),
        migrations.RemoveField(
            model_name='onlineproductionreport',
            name='no_of_billet',
        ),
        migrations.AddField(
            model_name='onlineproductionreport',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='onlineproductionreport',
            name='date_of_production',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Production'),
        ),
        migrations.AddField(
            model_name='onlineproductionreport',
            name='die_requisition_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Die Requisition ID'),
        ),
        migrations.AddField(
            model_name='onlineproductionreport',
            name='planned_qty',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Planned QTY'),
        ),
    ]
