# Generated by Django 5.2.5 on 2025-12-09 07:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def safe_migration(apps, schema_editor):
    """Safely handle table and column operations"""
    with schema_editor.connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables 
            WHERE table_schema = DATABASE()
            AND table_name = 'online_production_report'
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            # Create the table if it doesn't exist
            cursor.execute("""
                CREATE TABLE `online_production_report` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `production_id` varchar(20) NOT NULL UNIQUE,
                    `date` date NOT NULL,
                    `date_of_production` date DEFAULT NULL,
                    `die_no` varchar(100) DEFAULT '',
                    `section_no` varchar(100) DEFAULT '',
                    `section_name` varchar(200) DEFAULT '',
                    `planned_qty` int DEFAULT NULL,
                    `start_time` time DEFAULT NULL,
                    `end_time` time DEFAULT NULL,
                    `status` varchar(20) NOT NULL DEFAULT 'in_progress',
                    `created_at` datetime(6) NOT NULL,
                    `updated_at` datetime(6) NOT NULL,
                    `die_requisition_id` bigint DEFAULT NULL,
                    `operator_id` bigint DEFAULT NULL,
                    `press_id` bigint DEFAULT NULL,
                    `shift_id` bigint DEFAULT NULL,
                    `billet_size` varchar(50) DEFAULT '',
                    `cut_length` varchar(10) DEFAULT '',
                    `input_qty` decimal(10,2) DEFAULT NULL,
                    `no_of_billet` int DEFAULT NULL,
                    `no_of_cavity` varchar(10) DEFAULT '',
                    `no_of_pieces` int DEFAULT NULL,
                    `total_output` decimal(10,2) DEFAULT NULL,
                    `wt_per_piece_general` decimal(10,2) DEFAULT NULL,
                    `wt_per_piece_output` decimal(10,2) DEFAULT NULL,
                    PRIMARY KEY (`id`),
                    KEY `die_requisition_id` (`die_requisition_id`),
                    KEY `operator_id` (`operator_id`),
                    KEY `press_id` (`press_id`),
                    KEY `shift_id` (`shift_id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)
        else:
            # Table exists, handle column operations
            # Drop old columns if they exist
            columns_to_drop = ['customer_name', 'press_no_id', 'production_plan_id_id', 'wt_per_piece']
            for column in columns_to_drop:
                cursor.execute(f"""
                    SELECT COUNT(*)
                    FROM information_schema.columns 
                    WHERE table_schema = DATABASE()
                    AND table_name = 'online_production_report'
                    AND column_name = '{column}'
                """)
                column_exists = cursor.fetchone()[0]
                
                if column_exists:
                    cursor.execute(f"ALTER TABLE online_production_report DROP COLUMN `{column}`")
            
            # Add new columns if they don't exist
            columns_to_add = {
                'billet_size': "varchar(50) DEFAULT ''",
                'cut_length': "varchar(10) DEFAULT ''",
                'input_qty': "decimal(10,2) DEFAULT NULL",
                'no_of_billet': "int DEFAULT NULL",
                'no_of_cavity': "varchar(10) DEFAULT ''",
                'no_of_pieces': "int DEFAULT NULL",
                'total_output': "decimal(10,2) DEFAULT NULL",
                'wt_per_piece_general': "decimal(10,2) DEFAULT NULL",
                'wt_per_piece_output': "decimal(10,2) DEFAULT NULL",
            }
            
            for column_name, column_definition in columns_to_add.items():
                cursor.execute(f"""
                    SELECT COUNT(*)
                    FROM information_schema.columns 
                    WHERE table_schema = DATABASE()
                    AND table_name = 'online_production_report'
                    AND column_name = '{column_name}'
                """)
                column_exists = cursor.fetchone()[0]
                
                if not column_exists:
                    cursor.execute(f"ALTER TABLE online_production_report ADD COLUMN `{column_name}` {column_definition}")


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_capacity_companypress_sensor'),
        ('planning', '0006_productionplan_billet_size_productionplan_cut_length_and_more'),
        ('production', '0003_remove_onlineproductionreport_billet_size_and_more'),
    ]

    operations = [
        # Run custom SQL to handle everything
        migrations.RunPython(safe_migration, reverse_code=migrations.RunPython.noop),
    ]