# Generated by Django 5.2.5 on 2025-12-11 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_onlineproductionreport_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineproductionreport',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight'),
        ),
    ]
