# Generated by Django 5.2.5 on 2025-12-16 08:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_onlineproductionreport_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Report ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('die_no', models.CharField(blank=True, max_length=100, verbose_name='Die No')),
                ('section_no', models.CharField(blank=True, max_length=100, verbose_name='Section No')),
                ('section_name', models.CharField(blank=True, max_length=200, verbose_name='Section Name')),
                ('cavity', models.CharField(blank=True, max_length=10, verbose_name='Cavity')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('billet_size', models.CharField(blank=True, max_length=50, verbose_name='Billet Size (mm)')),
                ('no_of_billet', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='No of Billet')),
                ('input_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Input')),
                ('cut_length', models.CharField(blank=True, max_length=10, verbose_name='Cut Length')),
                ('wt_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='WT per Piece')),
                ('no_of_ok_pcs', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='No of OK PCS')),
                ('output', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Output')),
                ('recovery', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recovery (%)')),
                ('nop_bp', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='NOP BP')),
                ('nop_ba', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='NOP BA')),
                ('nrt', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='NRT (Hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('online_production_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='production.onlineproductionreport', verbose_name='Die No')),
            ],
            options={
                'verbose_name': 'Daily Production Report',
                'verbose_name_plural': 'Daily Production Reports',
                'db_table': 'daily_production_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductionReport',
        ),
    ]
