# Generated by Django 5.2.5 on 2025-12-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_dailyproductionreport_delete_productionreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyProductionReport',
        ),
    ]
