# Generated by Django 5.2.5 on 2025-11-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=50, verbose_name='Sensor Name')),
                ('datetime', models.DateTimeField(verbose_name='Date & Time')),
                ('t_factor', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='T-Factor')),
                ('die_name', models.CharField(max_length=100, verbose_name='Die Name')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Length (ft.in)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Record Created At')),
            ],
            options={
                'db_table': 'production_data',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Raw_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=50, verbose_name='Sensor Name')),
                ('datetime', models.DateTimeField(verbose_name='Date & Time')),
                ('t_factor', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='T-Factor')),
                ('die_number', models.CharField(max_length=50, verbose_name='Die Number')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Length (ft.in)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Record Created At')),
            ],
            options={
                'db_table': 'raw_machine_data',
            },
        ),
    ]
