# Generated by Django 5.2.5 on 2025-11-04 07:00

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alloy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloy_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Alloy ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('alloy_code', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Alloy Code')),
                ('temper_designation', models.CharField(blank=True, choices=[('Fabricated', 'Fabricated'), ('Annealed', 'Annealed'), ('Strain Hardened', 'Strain Hardened'), ('Solution Heat Treated', 'Solution Heat Treated'), ('Thermally Treated', 'Thermally Treated')], default='', max_length=50, verbose_name='Temper Designation')),
                ('temper_code', models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('T7', 'T7'), ('T8', 'T8'), ('T9', 'T9'), ('T10', 'T10')], default='', max_length=10, verbose_name='Temper Code')),
                ('tensile_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tensile Strength')),
                ('material', models.CharField(blank=True, default='', max_length=255, verbose_name='Material')),
                ('silicon_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Silicon (%)')),
                ('copper_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Copper (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alloy',
                'verbose_name_plural': 'Alloys',
                'db_table': 'alloy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Customer ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('customer_type', models.CharField(blank=True, choices=[('Manufacturer', 'Manufacturer'), ('Stockist', 'Stockist'), ('Supplier', 'Supplier'), ('Bulk Order', 'Ingots'), ('Retail', 'Retail')], max_length=50, verbose_name='Customer Type')),
                ('contact_no', models.CharField(blank=True, max_length=20, verbose_name='Contact No')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Customer Contact Person')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_name', models.CharField(max_length=100, unique=True, verbose_name='Press Name')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('profile_name', models.CharField(max_length=100, unique=True, verbose_name='Profile Name')),
                ('section_no', models.CharField(max_length=50, verbose_name='Section No')),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length (mm)')),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width (mm)')),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Thickness (mm)')),
                ('weight_type', models.CharField(choices=[('KG_12', "kg/12'"), ('KG_16', "kg/16'"), ('KG_18', "kg/18'")], max_length=20, verbose_name='Weight Type')),
                ('weight_value', models.CharField(max_length=50, verbose_name='Weight Value')),
                ('shape_image', models.ImageField(blank=True, null=True, upload_to='profile_shapes/', verbose_name='Shape Image')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Section ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('section_no', models.CharField(max_length=50, unique=True, verbose_name='Section No')),
                ('section_name', models.CharField(blank=True, max_length=255, verbose_name='Section Name')),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Section Image')),
                ('shape', models.CharField(blank=True, choices=[('T Profile', 'T Profile'), ('U Profile', 'U Profile'), ('C Profile', 'C Profile'), ('H Profile', 'H Profile'), ('L Profile', 'L Profile')], max_length=50, verbose_name='Shape')),
                ('type', models.CharField(blank=True, choices=[('Section', 'Section'), ('Channel', 'Channel'), ('Angle', 'Angle'), ('Mesh', 'Mesh'), ('Rod', 'Rod')], max_length=50, verbose_name='Type')),
                ('usage', models.CharField(blank=True, choices=[('Industrial', 'Industrial'), ('Construction', 'Construction'), ('Solar', 'Solar'), ('Automobile', 'Automobile')], max_length=50, verbose_name='Usage')),
                ('length_mm', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Length in mm')),
                ('width_mm', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Width in mm')),
                ('thickness_mm', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Thickness in mm')),
                ('ionized', models.BooleanField(default=False, verbose_name='Ionized')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'section',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Supplier ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('supplier_type', models.CharField(choices=[('Die Supplier', 'Die Supplier'), ('Raw Material', 'Raw Material'), ('Billets', 'Billets'), ('Ingots', 'Ingots'), ('Parts', 'Parts'), ('Service', 'Service')], max_length=50, verbose_name='Supplier Type')),
                ('contact_no', models.CharField(max_length=20, verbose_name='Contact No')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Supplier Contact Person')),
                ('address', models.TextField(verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supplier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presses', to='master.company')),
            ],
            options={
                'verbose_name_plural': 'Company Presses',
            },
        ),
        migrations.CreateModel(
            name='CompanyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timing', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='master.company')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_no', models.CharField(max_length=100, verbose_name='Cost No')),
                ('date_of_extrusion', models.DateField(default=django.utils.timezone.now)),
                ('aging_no', models.CharField(max_length=100, verbose_name='Aging No')),
                ('lot_number', models.CharField(max_length=255, unique=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('press_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='master.press')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Staff ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('staff_register_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Staff Register No')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('contact_no', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number', regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact No')),
                ('designation', models.CharField(choices=[('Worker', 'Worker'), ('Machine Operator', 'Machine Operator'), ('Supervisor', 'Supervisor'), ('Incharge', 'Incharge')], max_length=50, verbose_name='Designation')),
                ('shift_assigned', models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Night')], max_length=20, verbose_name='Shift Assigned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='master.companypress', verbose_name='Assigned To Press')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Die ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Date')),
                ('die_no', models.CharField(max_length=100, unique=True, verbose_name='Die No')),
                ('die_name', models.CharField(blank=True, max_length=200, verbose_name='Die Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='die_images/', verbose_name='Image')),
                ('project_no', models.CharField(blank=True, max_length=100, verbose_name='Project No')),
                ('date_of_receipt', models.DateField(blank=True, null=True, verbose_name='Date of Receipt')),
                ('no_of_cavity', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], max_length=10, verbose_name='No of Cavity')),
                ('req_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Req Weight')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Size')),
                ('die_material', models.CharField(blank=True, choices=[('SS', 'SS'), ('CI', 'CI'), ('GI', 'GI')], max_length=10, verbose_name='Die Material')),
                ('hardness', models.CharField(blank=True, max_length=100, verbose_name='Hardness')),
                ('type', models.CharField(blank=True, choices=[('Dieplate', 'Dieplate'), ('Manderel', 'Manderel'), ('Backer', 'Backer'), ('Feeder', 'Feeder')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dies', to='master.companypress', verbose_name='Press')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dies', to='master.supplier', verbose_name='Supplier Name')),
            ],
            options={
                'verbose_name': 'Die',
                'verbose_name_plural': 'Dies',
                'ordering': ['-created_at'],
            },
        ),
    ]
