# Generated by Django 5.2.5 on 2025-10-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alloy',
            name='updated_at',
        ),
    ]
