# Generated by Django 5.2.5 on 2025-11-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypress',
            old_name='capacity',
            new_name='sensor',
        ),
    ]
