# Generated by Django 5.2.5 on 2025-10-06 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_alloy_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gst_or_pan',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(default='', max_length=20, verbose_name='Contact No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Customer Contact Person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='', editable=False, max_length=20, unique=True, verbose_name='Customer ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Stockist', 'Stockist'), ('Supplier', 'Supplier'), ('Bulk Order', 'Ingots'), ('Retail', 'Retail')], default='Regular', max_length=50, verbose_name='Customer Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Unknown Customer', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
