# Generated by Django 5.2.5 on 2025-10-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='die',
            name='store_location',
        ),
    ]
