# Generated by Django 5.2.5 on 2025-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_remove_die_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='die',
            name='store_location',
            field=models.CharField(default='Warehouse', max_length=100, verbose_name='Store Location'),
            preserve_default=False,
        ),
    ]
