# Generated by Django 5.2.5 on 2025-10-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_die_store_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='die',
            name='store_location',
        ),
    ]
