# Generated by Django 5.2.5 on 2025-10-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_die_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='die',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
