# Generated by Django 5.2.5 on 2025-10-31 11:27

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_die_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='die',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='die',
            name='die_material',
            field=models.CharField(blank=True, choices=[('SS', 'SS'), ('CI', 'CI'), ('GI', 'GI')], max_length=10, verbose_name='Die Material'),
        ),
        migrations.AlterField(
            model_name='die',
            name='die_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Die Name'),
        ),
        migrations.AlterField(
            model_name='die',
            name='hardness',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hardness'),
        ),
        migrations.AlterField(
            model_name='die',
            name='no_of_cavity',
            field=models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], max_length=10, verbose_name='No of Cavity'),
        ),
        migrations.AlterField(
            model_name='die',
            name='req_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Req Weight'),
        ),
        migrations.AlterField(
            model_name='die',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='die',
            name='type',
            field=models.CharField(blank=True, choices=[('Dieplate', 'Dieplate'), ('Manderel', 'Manderel'), ('Backer', 'Backer'), ('Feeder', 'Feeder')], max_length=20, verbose_name='Type'),
        ),
    ]
