# Generated by Django 5.2.5 on 2025-10-31 11:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_die_date_alter_die_die_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloy',
            name='alloy_code',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Alloy Code'),
        ),
        migrations.AlterField(
            model_name='alloy',
            name='copper_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Copper (%)'),
        ),
        migrations.AlterField(
            model_name='alloy',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='alloy',
            name='material',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='alloy',
            name='silicon_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Silicon (%)'),
        ),
        migrations.AlterField(
            model_name='alloy',
            name='temper_code',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('T7', 'T7'), ('T8', 'T8'), ('T9', 'T9'), ('T10', 'T10')], default='', max_length=10, verbose_name='Temper Code'),
        ),
        migrations.AlterField(
            model_name='alloy',
            name='temper_designation',
            field=models.CharField(blank=True, choices=[('Fabricated', 'Fabricated'), ('Annealed', 'Annealed'), ('Strain Hardened', 'Strain Hardened'), ('Solution Heat Treated', 'Solution Heat Treated'), ('Thermally Treated', 'Thermally Treated')], default='', max_length=50, verbose_name='Temper Designation'),
        ),
        migrations.AlterField(
            model_name='alloy',
            name='tensile_strength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tensile Strength'),
        ),
    ]
