# Generated by Django 5.2.5 on 2025-10-31 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_alloy_alloy_code_alter_alloy_copper_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Manufacturer', 'Manufacturer'), ('Stockist', 'Stockist'), ('Supplier', 'Supplier'), ('Bulk Order', 'Ingots'), ('Retail', 'Retail')], max_length=50, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
    ]
