# Generated by Django 5.2.5 on 2025-11-04 07:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_requisition_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Die Requisition ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('section_name', models.CharField(max_length=200, verbose_name='Section Name')),
                ('wt_range', models.CharField(max_length=50, verbose_name='WT Range')),
                ('die_name', models.CharField(max_length=200, verbose_name='Die Name')),
                ('present_wt', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Present WT')),
                ('no_of_cavity', models.CharField(max_length=10, verbose_name='No of Cavity')),
                ('cut_length', models.CharField(blank=True, choices=[('12ft', '12 ft'), ('16ft', '16 ft'), ('18ft', '18 ft')], max_length=10, null=True, verbose_name='Cut Length')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_requisition_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='order_management.requisition', verbose_name='Customer Requisition No')),
                ('die_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.die', verbose_name='Die No')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.companypress', verbose_name='Press')),
                ('section_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.section', verbose_name='Section No')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.companyshift', verbose_name='Shift')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.staff', verbose_name='Staff Name')),
            ],
            options={
                'verbose_name': 'Die Requisition',
                'verbose_name_plural': 'Die Requisitions',
                'db_table': 'die_requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_plan_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Production Plan ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Customer Name')),
                ('die_no', models.CharField(blank=True, max_length=100, verbose_name='Die No')),
                ('wt_range', models.CharField(blank=True, max_length=50, verbose_name='WT Range')),
                ('cut_length', models.CharField(blank=True, max_length=10, verbose_name='Cut Length')),
                ('wt_per_piece', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='WT per Piece')),
                ('qty', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='QTY')),
                ('billet_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Billet Size')),
                ('no_of_billet', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='No Of Billet')),
                ('plan_recovery', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plan Recovery')),
                ('current_recovery', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Recovery')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('discard', 'Discard')], default='planned', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cust_requisition_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='order_management.requisition', verbose_name='Customer Requisition ID')),
                ('die_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='planning.dierequisition', verbose_name='Die Requisition ID')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='master.companypress', verbose_name='Press')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='master.companyshift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Production Plan',
                'verbose_name_plural': 'Production Plans',
                'db_table': 'production_plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
