# Generated by Django 5.2.5 on 2025-10-08 09:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0003_alter_customer_options_and_more'),
        ('order_management', '0003_remove_requisition_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_requisition_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Die Requisition ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('section_name', models.CharField(max_length=200, verbose_name='Section Name')),
                ('wt_range', models.CharField(max_length=50, verbose_name='WT Range')),
                ('die_name', models.CharField(max_length=200, verbose_name='Die Name')),
                ('present_wt', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Present WT')),
                ('no_of_cavity', models.CharField(max_length=10, verbose_name='No of Cavity')),
                ('qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='QTY')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_requisition_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='order_management.requisition', verbose_name='Customer Requisition No')),
                ('die_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.die', verbose_name='Die No')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.companypress', verbose_name='Press')),
                ('section_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.section', verbose_name='Section No')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.companyshift', verbose_name='Shift')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_requisitions', to='master.staff', verbose_name='Staff Name')),
            ],
            options={
                'verbose_name': 'Die Requisition',
                'verbose_name_plural': 'Die Requisitions',
                'db_table': 'die_requisition',
                'ordering': ['-created_at'],
            },
        ),
    ]
