# Generated by Django 5.2.5 on 2025-10-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dierequisition',
            name='qty',
        ),
    ]
