# Generated by Django 5.2.5 on 2025-11-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_remove_productionplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplan',
            name='billet_size',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='current_recovery',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='no_of_billet',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='plan_recovery',
        ),
    ]
