# Generated by Django 5.2.5 on 2025-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_remove_dierequisition_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dierequisition',
            name='cut_length',
            field=models.CharField(choices=[('12ft', '12 ft'), ('16ft', '16 ft'), ('18ft', '18 ft')], default='12ft', max_length=10, verbose_name='Cut Length'),
            preserve_default=False,
        ),
    ]
