# Generated by Django 5.2.5 on 2025-10-09 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_customer_options_and_more'),
        ('order_management', '0003_remove_requisition_updated_at'),
        ('planning', '0003_dierequisition_cut_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_plan_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Production Plan ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('die_no', models.CharField(max_length=100, verbose_name='Die No')),
                ('wt_range', models.CharField(max_length=50, verbose_name='WT Range')),
                ('cut_length', models.CharField(max_length=10, verbose_name='Cut Length')),
                ('wt_per_piece', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='WT per Piece')),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='QTY')),
                ('billet_size', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Billet Size')),
                ('no_of_billet', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='No Of Billet')),
                ('plan_recovery', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plan Recovery')),
                ('current_recovery', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Recovery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cust_requisition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='order_management.requisition', verbose_name='Customer Requisition ID')),
                ('die_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='planning.dierequisition', verbose_name='Die Requisition ID')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='master.companypress', verbose_name='Press')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='master.companyshift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Production Plan',
                'verbose_name_plural': 'Production Plans',
                'db_table': 'production_plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
