# Generated by Django 5.2.5 on 2025-11-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_remove_productionplan_billet_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dierequisition',
            name='press',
        ),
        migrations.RemoveField(
            model_name='dierequisition',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='dierequisition',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='dierequisition',
            name='staff_name',
        ),
    ]
