# Generated by Django 5.2.5 on 2025-11-29 06:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_capacity_companypress_sensor'),
        ('order_management', '0004_requisition_status'),
        ('planning', '0004_remove_dierequisition_press_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplan',
            name='cut_length',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='wt_range',
        ),
        migrations.AddField(
            model_name='productionplan',
            name='date_of_production',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Production'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_plans', to='master.staff', verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='planned_qty',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Planned QTY'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='section_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section Name'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='section_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Section No'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='cust_requisition_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='order_management.requisition', verbose_name='Cust Requisition ID'),
        ),
    ]
