# Generated by Django 5.2.5 on 2025-10-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_productionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('discard', 'Discard')], default='planned', max_length=20, verbose_name='Status'),
        ),
    ]
