# Generated by Django 5.2.5 on 2025-12-08 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_remove_productionplan_cut_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='billet_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Billet Size (mm)'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='cut_length',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cut Length'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='no_of_billet',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='No of Billet'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='no_of_cavity',
            field=models.CharField(blank=True, max_length=10, verbose_name='No of Cavity'),
        ),
    ]
