# Generated by Django 5.2.5 on 2025-10-06 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('sales_manager', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(choices=[('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=2)),
                ('delivery_date', models.DateField()),
                ('dispatch_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('wt_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Weight Range')),
                ('cut_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cut Length')),
                ('pack', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pack')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('total_pack', models.IntegerField(blank=True, null=True, verbose_name='Total Pack')),
                ('total_no', models.IntegerField(blank=True, null=True, verbose_name='Total No')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alloy_temper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.alloy', verbose_name='Alloy Temper')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_items', to='order_management.requisition')),
                ('section_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.profile', verbose_name='Section No')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('sales_manager', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(choices=[('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=2)),
                ('delivery_date', models.DateField()),
                ('dispatch_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('tax_type', models.CharField(choices=[('SGST', 'SGST'), ('CGST', 'CGST'), ('IGST', 'IGST')], max_length=4, verbose_name='Tax Type')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='order_management.workorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('wt_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Weight Range')),
                ('cut_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cut Length')),
                ('pack', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pack')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('total_pack', models.IntegerField(blank=True, null=True, verbose_name='Total Pack')),
                ('total_no', models.IntegerField(blank=True, null=True, verbose_name='Total No')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alloy_temper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.alloy', verbose_name='Alloy Temper')),
                ('section_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.profile', verbose_name='Section No')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_items', to='order_management.workorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
