# Generated by Django 5.2.5 on 2025-11-04 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Customer Requisition ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('requisition_no', models.CharField(max_length=50, unique=True, verbose_name='Customer Requisition No')),
                ('contact_no', models.CharField(max_length=20, verbose_name='Contact No')),
                ('address', models.TextField(verbose_name='Address')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('dispatch_date', models.DateField(blank=True, null=True, verbose_name='Dispatch Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer', verbose_name='Customer')),
                ('sales_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.staff', verbose_name='Sales Manager')),
            ],
            options={
                'verbose_name': 'Customer Requisition',
                'verbose_name_plural': 'Customer Requisitions',
                'db_table': 'requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wt_range', models.CharField(max_length=50, verbose_name='WT Range')),
                ('cut_length', models.CharField(choices=[('12ft', '12 ft'), ('16ft', '16 ft'), ('18ft', '18 ft')], max_length=10, verbose_name='Cut Length')),
                ('qty_in_no', models.IntegerField(verbose_name='QTY in No')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_management.requisition', verbose_name='Requisition')),
                ('section_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_orders', to='master.section', verbose_name='Section No')),
            ],
            options={
                'verbose_name': 'Requisition Order',
                'verbose_name_plural': 'Requisition Orders',
                'db_table': 'requisition_order',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('sales_manager', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(choices=[('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=2)),
                ('delivery_date', models.DateField()),
                ('dispatch_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('tax_type', models.CharField(choices=[('SGST', 'SGST'), ('CGST', 'CGST'), ('IGST', 'IGST')], max_length=4, verbose_name='Tax Type')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='order_management.workorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('wt_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Weight Range')),
                ('cut_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cut Length')),
                ('pack', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pack')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('total_pack', models.IntegerField(blank=True, null=True, verbose_name='Total Pack')),
                ('total_no', models.IntegerField(blank=True, null=True, verbose_name='Total No')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alloy_temper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.alloy', verbose_name='Alloy Temper')),
                ('section_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.profile', verbose_name='Section No')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_items', to='order_management.workorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
