# Generated by Django 5.2.5 on 2025-10-07 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_customer_options_and_more'),
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Requisition', 'verbose_name_plural': 'Customer Requisitions'},
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='requisition',
            name='date',
            field=models.DateField(default='2025-10-07', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='requisition_id',
            field=models.CharField(default='REQ00001', editable=False, max_length=20, unique=True, verbose_name='Customer Requisition ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='requisition_no',
            field=models.CharField(default='REQ00001', max_length=50, unique=True, verbose_name='Customer Requisition No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='contact_no',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Contact No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dispatch Date'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sales_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.staff', verbose_name='Sales Manager'),
        ),
        migrations.AlterModelTable(
            name='requisition',
            table='requisition',
        ),
        migrations.CreateModel(
            name='RequisitionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wt_range', models.CharField(max_length=50, verbose_name='WT Range')),
                ('cut_length', models.CharField(choices=[('12ft', '12 ft'), ('16ft', '16 ft'), ('18ft', '18 ft')], max_length=10, verbose_name='Cut Length')),
                ('qty_in_no', models.IntegerField(verbose_name='QTY in No')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_management.requisition', verbose_name='Requisition')),
                ('section_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_orders', to='master.section', verbose_name='Section No')),
            ],
            options={
                'verbose_name': 'Requisition Order',
                'verbose_name_plural': 'Requisition Orders',
                'db_table': 'requisition_order',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='RequisitionGoods',
        ),
    ]
