# Generated by Django 5.2.5 on 2025-11-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_requisition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='status',
        ),
    ]
