# Generated by Django 5.2.5 on 2025-10-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_requisition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='updated_at',
        ),
    ]
