# Generated by Django 5.2.5 on 2025-11-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_remove_requisition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_planning', 'In Planning'), ('in_production', 'In Production'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='created', max_length=20, verbose_name='Status'),
        ),
    ]
